### ISSUE TITLE
Support loading image data from a string

### ISSUE THREAD

**Issue by wasamasa** [wachikun/emacs_bgex#2]
This feature would allow for dynamically generating images to insert and bypass loading from disk completely.  An example can be found in `xpm_load` in `image.c` where an additional parameter to FILENAME is introduced, DATA. If FILENAME is empty and DATA a string, DATA is used for the image contents.

**Comment by wachikun** [comment]
Add support for XPM string(test)
https://github.com/wachikun/emacs_bgex/tree/test-dynamic-xpm

```shell
$ cd src
$ patch < test-dynamic-xpm-patch-bgex_20150621_0
$ cd ..
$ make
$ src/emacs
```
And load test-dynamic-xpm.el

**Comment by wasamasa** [comment]
Hmm, I can patch and compile Emacs from git just fine, but loading test-dynamic-xpm.el does nothing...

**Comment by wachikun** [comment]
Please eval before load test-dynamic-xpm.el.
```elisp
(bgex-set-image-default "/tmp/AVOID_BUG.png" t)
```
BGEX seem to need this...
I didn't know this old bug...orz

**Comment by wasamasa** [comment]
Thanks, that makes it work again. Feel free to close this once it works without the workaround and for all patches.
